apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  servicename: "nginx"
  replicas: 2
  selector: 
    matchlable:
      app: nginx
  template:
    metadata:
      lable:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: repo/nginx:latest
          ports:
            conatainerport: 80
          resource:
            requests:
              cpu: 500m
              memory: 250Mi
            limits:
              cpu: 250m
              memory: 128Mi
          volumemounts:
          - name: nginx-storage
            mountpath: /usr/share/nginx/html
